### ISSUE TITLE
Prefer `println` to `print`

### ISSUE THREAD

**Issue by ISSOtm** [mdagois/gca#5]
https://github.com/mdagois/gca/blob/55d70a5d5e706ee641eb771a67380000437d3f82/samples/dma_double_sprite/sample.rgbasm#L75

`print` does not do any special handling on Windows, so the LF may not be correctly translated to CRLF; `println` does that special handling.

There may be more examples than the above, but this is one that I noticed.

**Comment by mdagois** [comment]
I replaced all `print` with `println`. The change will be reflected in v3.1.

**Comment by mdagois** [comment]
Fixed in v3.1.
